In [15]:
import face_recognition as fc
import cv2
import dlib as db
import numpy as np
import os
from datetime import datetime

In [16]:
path = 'imageAttendence'
images = []
classNames = []
mylist = os.listdir(path)
print(mylist)

['aryan.jpg', 'kr.jpg', 'rachit.jpg', 'sudha.jpg']


In [17]:
for cl in mylist:
    curImg = cv2.imread(f'{path}/{cl}')
    images.append(curImg)
    classNames.append(os.path.splitext(cl)[0])
print(classNames)    

['aryan', 'kr', 'rachit', 'sudha']


In [ ]:
def findEncodings(images):
    encodeList = []
    for img in images:
        img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
        encode = fc.face_encodings(img)[0]
        encodeList.append(encode)
    return encodeList

def markAttendence(name):
    with open('Attendence.csv','r+') as f:
        myDataList = f.readlines()
        nameList = []
        for line in myDataList:
            entry = line.split(',')
            nameList.append(entry[0])
        if name not in nameList:
            now = datetime.now()
            dtString = now.strftime('%H:%M:%S')
            f.writelines(f'\n{name},{dtString}')
    

encodeListKnown = findEncodings(images)
print('Encoding Complete')
 
cap = cv2.VideoCapture(0)

while True:
    success, img = cap.read()
    imgS = cv2.resize(img,(0,0),None,0.25,0.25)
    imgS = cv2.cvtColor(imgS, cv2.COLOR_BGR2RGB) 
    
    facesCurFrame = fc.face_locations(imgS)
    encodesCurFrame = fc.face_encodings(imgS,facesCurFrame)
    
    for encodeFace,faceloc in zip(encodesCurFrame,facesCurFrame):
        matches = fc.compare_faces(encodeListKnown,encodeFace)
        faceDis = fc.face_distance(encodeListKnown,encodeFace)
        print(faceDis)
        matchIndex = np.argmin(faceDis)
        
        if matches[matchIndex]:
            name = classNames[matchIndex].upper()
            print(name)
            y1,x2,y2,x1 = faceloc
            y1,x2,y2,x1 = y1*4,x2*4,y2*4,x1*4
            cv2.rectangle(img,(x1,y1),(x2,y2),(0,255,0),2)
            cv2.rectangle(img,(x1,y2-35),(x2,y2),(0,255,0),cv2.FILLED)
            cv2.putText(img,name,(x1+6,y2-6),cv2.FONT_HERSHEY_COMPLEX,1,(255,255,255),2)
            markAttendence(name)
            
    cv2.imshow('webcam',img)
    cv2.waitKey(1)

Encoding Complete
[0.51372482 0.61258785 0.41111694 0.63194654]
RACHIT
[0.67287577 0.52585458 0.68566668 0.82661752]
KR
[0.55738026 0.56784183 0.47501404 0.68560158]
RACHIT
[0.63707584 0.56250727 0.65797012 0.79426089]
KR
[0.53627087 0.61090531 0.46636318 0.66892609]
RACHIT
[0.65549123 0.56291476 0.69008578 0.8145851 ]
KR
[0.50168626 0.5526389  0.49176015 0.69763993]
RACHIT
[0.4888282  0.59394525 0.45111477 0.68320459]
RACHIT
[0.52611478 0.56970018 0.52235531 0.76119632]
RACHIT
[0.48841108 0.57654766 0.50728114 0.72366139]
ARYAN
[0.63021908 0.56793732 0.64248968 0.79849777]
KR
[0.69010402 0.58241125 0.69750161 0.81889769]
KR
[0.47763047 0.54825558 0.53888476 0.6677184 ]
ARYAN
[0.48302488 0.57676085 0.52040222 0.70003509]
ARYAN
[0.5957589  0.57906139 0.56728762 0.74820759]
RACHIT
[0.50205324 0.54933317 0.53093119 0.70624716]
ARYAN
[0.4844309  0.60646438 0.51371874 0.71290495]
ARYAN
[0.51077338 0.5696319  0.53443729 0.66077161]
ARYAN
[0.63389574 0.6434078  0.55723039 0.79745577]
RACHIT
[